# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-10 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170810_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='No Bios', help_text='Short Descriptions about yourself', null=True),
        ),
    ]
