# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-10 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170810_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='attribute',
            field=models.CharField(choices=[('NONE', 'none'), ('USER', 'user'), ('TRUCK-DRIVER', 'truck_driver')], default='NONE', max_length=13),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'M'), ('Female', 'F'), ('Undefined', 'N')], default='N', max_length=1),
        ),
    ]
