# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-10 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170810_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'M'), ('Female', 'F'), ('Undefined', 'N')], default='Undefined', max_length=1),
        ),
    ]
