# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-14 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170810_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='attribute',
            field=models.CharField(choices=[('NONE', 'none'), ('USER', 'user'), ('DRIVER', 'truck_driver')], default='NONE', max_length=13),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F'), ('U', 'N')], default='Undefined', max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='/media/User-Profiles/default.png', null=True, upload_to='User-Profiles'),
        ),
    ]
