# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-16 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170814_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F'), ('U', 'N')], default='U', max_length=1),
        ),
    ]
