# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-20 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import resolutions.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170816_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='/media/User-Profiles/default.png', null=True, upload_to=resolutions.helpers.RandomFileName('User-Profiles')),
        ),
    ]
