# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-08 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtruck', '0002_truck_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='name',
            field=models.CharField(help_text='Name Your Truck', max_length=250),
        ),
    ]
