# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-20 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import resolutions.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('foodtruck', '0004_auto_20170814_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='image',
            field=models.ImageField(blank=True, default='/media/Truck-Images/Default.jpg', null=True, upload_to=resolutions.helpers.RandomFileName('Truck-Images')),
        ),
    ]
