# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-21 01:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import resolutions.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foodtruck', '0005_auto_20170920_1201'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Menu Card Name', max_length=250)),
                ('image', models.ImageField(blank=True, default='/media/Menu-Images/default.jpg', null=True, upload_to=resolutions.helpers.RandomFileName('Menu-Images'))),
                ('description', models.TextField()),
                ('is_dish', models.BooleanField(default=False)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodtruck.Truck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
